config/routes.rb
Rails.application.routes.draw do
  get 'emps/show'
  resources :challenges do
    resources :votes, only: [:create, :destroy], shallow: true
    resources :collaborations, only: [:create, :destroy], shallow: true
  end
  devise_for :emps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "challenges#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :emp
  has_many :tags, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :collaborations, dependent: :destroy

  validates_presence_of :title, :description

  def is_liked(emp)
    Vote.find_by(emp_id: emp.id, challenge_id: id)
  end

  def is_collaboration(emp)
    Collaboration.find_by(emp_id: emp.id, challenge_id: id)
  end
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :emp
  belongs_to :challenge
  validates_presence_of :emp_id, :challenge_id
end

app/models/emp.rb
class Emp < ApplicationRecord
  has_many :challenges, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :collaborations, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
  attr_writer :login

  validates :empid , presence: true, uniqueness: {case_sensitive:false}
  validates_presence_of :empid, :email, :password, :password_confirmation
  def login
    @login || self.empid ||self.email
  end  

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(empid) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :challenge
  validates_presence_of :name
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :emp
  belongs_to :challenge
  #validates_uniqueness_of :votes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        added_attrs= [:empid,:email, :password, :password_confirmation, :remember_me]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_emp!, only:[:edit, :update, :destroy]
  
  def index
    #  if params[:sortable] == "votes"  
    #     @challenges = Challenge.all.sort_by { |challenge| challenge.votes.count }.reverse   
    #  else
    @challenges = Challenge.order(sort_column+ " " + sort_direction).paginate(page: params[:page], per_page: 5)
    #@challenges2 = Challenge.paginate(page: params[:page], per_page: 5)
  end

 
  def show
  end

  def new
    @challenge = Challenge.new
  end

  
  def edit
  end


  def create
    @challenge = ChallengeCreator.new(params).execute(current_emp)
    if @challenge
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Challenge was successfully created." }
        #format.json { render :show, status: :created, location: @challenge }
      end
    else
      respond_to do |format|
        format.html { render :new }
        #format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(:title, :description, :emp_id, :tag)
    end

    def sort_column
      params[:sort] || "title"
    end
    
    def sort_direction
      params[:direction] || "asc"
    end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
    before_action :authenticate_emp!

    def create
        @collaboration = current_emp.collaborations.build(collaboration_params)
        @challenge =@collaboration.challenge
        if current_emp.id != @challenge.emp.id
            if @collaboration.save
                #flash[:notice]="voted"
                redirect_to root_path 
                flash.now[:notice] = "Collaborated"
            else 
                flash.now[:notice] = "something went wrong"
            end
        else
            redirect_to root_path 
            flash[:notice] =  "You cannot collaborate your challenge"
        end
    end

    def destroy
        @collaboration =Collaboration.find(params[:id])
        @post = @collaboration.challenge
        if @collaboration.destroy
            #flash[:notice]="vote deleted"
            redirect_to root_path notice: "Collaboration Declined"
        else
            flash[:notice]= "Somethign went wrong"
        end
    end
    
    private

    def collaboration_params
        params.permit :challenge_id
    end
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
    def show
    end
end 

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :authenticate_emp!

    def create
        @vote = current_emp.votes.build(vote_params)
        @challenge =@vote.challenge
        if current_emp.id != @challenge.emp.id
            if @vote.save
                emp_mailer = EmpMailer.vote_confirmation(Emp.last)
                emp_mailer.deliver()
                redirect_to root_path 
                flash[:success]= "Voted"
            else 
                flash[:danger] = "something went wrong"
            end
        else
            redirect_to root_path 
            flash[:notice]= "You cannot upvote your challenge"
        end
    end

    def destroy
        @vote =Vote.find(params[:id])
        @post = @vote.challenge
        if @vote.destroy
            #flash[:notice]="vote deleted"
            redirect_to root_path notice: "Downvoted"
        else
            flash[:notice]= "Somethign went wrong"
        end
    end
    
    private

    def vote_params
        params.permit :challenge_id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        capture do
            link_to({sort: column, direction: direction}) do
              concat title
              concat " "
              concat arrow(column)
            end
        end
    end
end
        
def arrow(column)
    return '' if params[:sort] != column
    arrow = params[:direction] == 'asc' ? 'down' : 'up'
        "<i class='fa fa-arrow-#{arrow}'></i>".html_safe
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_with(model: challenge) do |form| %>
  

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :emp_id %>
    <%= form.text_field :emp_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand"><%= link_to "Home", root_path, class:"text-light" %></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav mr-auto">
    
  </ul>
  <span class="navbar-text">
    <% if current_emp %>
       <%= link_to "#{current_emp.empid} Sign Out", destroy_emp_session_path, method: :delete %>
    <% else %>
       <span class="button1"><%= link_to "Login", new_emp_session_path, method: :post %></span>
       <span class="button2"><%= link_to "Sign Up", new_emp_registration_path %></span>
    <% end %>
  </span>
</div>
</nav>

<% flash.each do |type,msg| %>
      <div class="alert alert-info"><%= msg %></div>  
<% end %>

<%if current_emp %>
  <%= form_with model: Challenge do |form|%>
    <div class="row mt-5 ml-2 mb-5">
      <div class="col"><b>Title</b>
         <%=form.text_field :title, placeholder: "Title", class: "form-control"%>
      </div>
      <div class="col"><b>Description</b>
         <%=form.text_field :description, placeholder: "Description", class: "form-control", :minlength => 5 %>
      </div>
     
      <div class="col mt-4 form-control"><b>Tag</b>
         <%=form.select :tag, ['Array','Dynamic','String','Recursion','Queue','Linkedlist','Graphs','Stack','Rails','Ruby'], placeholder: "Tag", class: "p-4"%>
      </div>
      
         <%=form.hidden_field :emp_id, value: current_emp.id%>
      <div class="col mt-4">
         <%=form.submit "Add Challenge", class: "btn btn-primary bg-dark"%>
      </div>
    </div>
  <% end %>
<% end %>

<% if current_emp %>
  <h1>CHALLENGES</h1>
  <table class = "table table-hover text-center mt-3 ml-2">
   <thead class="align-center thead-dark" style="color:white">
      <tr class="align-center">
        <th><%= sortable "id" %></th>
        <th><%= sortable "title" %></th>
        <th><%= sortable "votes" %></th>
        <th><%= sortable "collaboration" %></th>
        <th><%= sortable "description" %></th>
        <th><%= sortable "employee" %></th>
        <th><%= sortable "tag" %></th> 
        <th><%= sortable "votes", "Votes Count" %></th>
        <th><%= sortable "created_at"%></th>
        <th><%= sortable "updated_at"%></th>
      </tr>
    <thead>
    <tbody class="align-center">
      <% @challenges.each do |challenge| %>
        <tr>
          <td><%= challenge.id%>
          <td><%= link_to challenge.title.truncate_words(4), challenge_path(challenge), class:"text-dark" %></td>
          <% if current_emp %>
          <td><% if challenge.is_liked(current_emp).present? %>
                  <%=link_to vote_path(challenge.is_liked(current_emp)), method: :delete, remote: :true do%>
                    <i class="fa fa-minus-circle fa-2x text-dark" aria-hidden="true"></i>
                  <%end%>
              <% else %>
              <%= link_to challenge_votes_path(challenge), method: :post, remote: :true do %>
                    <i class="fa fa-plus-circle fa-2x text-dark" aria-hidden="true"></i>
              <%end %>  
              <% end %> 
          </td>
          <td>
            <% if challenge.is_collaboration(current_emp).present? %>
                    <%= link_to collaboration_path(challenge.is_collaboration(current_emp)), method: :delete, remote: :true do %>
                      <i class="fa fa-check fa-2x text-dark" aria-hidden="true"></i>
                    <% end %>
      
                  <% else %>
                    <%= link_to challenge_collaborations_path(challenge), method: :post, remote: :true do %>
                      <i class="fa fa-times fa-2x text-dark" aria-hidden="true"></i>
                  <% end %>
              <% end %>
               <% challenge.collaborations.each do |collab_request| %>
                      E0<%= collab_request.emp_id %>
               <% end %>
          </td>
          <% end %>
          <td><%= challenge.description.truncate_words(5) %></td>
          <td><p>EO<%= challenge.emp_id %></p></td>
          <td><% challenge.tags.each do |tag| %>
                  <%= tag.name %>
              <% end %>
          </td>
          <td><%= challenge.votes.count%></td>
          <td><%= challenge.created_at.strftime("%d %B %y %A") %></td>
          <td><%= challenge.updated_at.strftime("%d %B %y %A") %></td>
                  
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<div class="center"><%= will_paginate(@challenges, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) if current_emp %></div>

<br>

<div class="footer">
   @copyright 2021 Navin Ojha
</div>

app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @challenge.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @challenge.description %>
</p>

<p>
  <strong>Tags:</strong>
  <% @challenge.tags.each do |tag| %>
     <%= tag.name %>
  <% end %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @challenge.emp_id %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge), class:"btn btn-dark" %> |
<%= link_to 'Back', challenges_path, class: "btn btn-dark" %>

app/views/emps/show.html.erb
<h1>Emps#show </h1>

<p>Emps show page</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackthon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>